# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: textgen.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rtextgen.proto\x12\x07textgen\"-\n\x0bTextRequest\x12\x0e\n\x06prompt\x18\x01 \x01(\t\x12\x0e\n\x06length\x18\x02 \x01(\x05\"\x1c\n\x0cTextResponse\x12\x0c\n\x04text\x18\x01 \x01(\t2N\n\rTextGenerator\x12=\n\x0cGenerateText\x12\x14.textgen.TextRequest\x1a\x15.textgen.TextResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'textgen_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TEXTREQUEST._serialized_start=26
  _TEXTREQUEST._serialized_end=71
  _TEXTRESPONSE._serialized_start=73
  _TEXTRESPONSE._serialized_end=101
  _TEXTGENERATOR._serialized_start=103
  _TEXTGENERATOR._serialized_end=181
# @@protoc_insertion_point(module_scope)
